import type { Metadata } from "next";
import { JetBrains_Mono as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/Navbar";
import { TransitionPages } from "@/components/TransitionPages";
import { StairTransiiton } from "@/components/animations/StairTransiiton";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Jit B Jony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-primary  antialiased", fontSans.variable)}>
        <Navbar />
        <StairTransiiton />
        <TransitionPages>{children}</TransitionPages>
      </body>
    </html>
  );
}
